version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    networks:
      - app_network
  nginx: 
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nextjs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge